### ISSUE TITLE
unable to open file: name = 'data/breakout/120k/states.h5'

### ISSUE THREAD

**Issue by wichersn** [TomZahavy/GrayingTheBox#1]
I get this error when I run main.py

```
python main.py
Preparing global features... 
Loading from hdf5 files... 
    Loading states
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    global_feats, hand_crafted_feats = prepare_data(game_id, run_dir, num_frames, load_data, debug_mode)
  File "/usr/local/google/home/wichersn/GrayingTheBox/prepare_data.py", line 39, in prepare_data
    global_feats = prepare_global_features(data_dir, num_frames, num_actions, num_lives, grad_thresh)
  File "/usr/local/google/home/wichersn/GrayingTheBox/prepare_global_features.py", line 10, in prepare_global_features
    states_hd5f = common.load_hdf5('states', data_dir, num_frames)
  File "/usr/local/google/home/wichersn/GrayingTheBox/common.py", line 10, in load_hdf5
    obj_file = h5py.File(path + object_name + '.h5', 'r')
  File "/usr/local/google/home/wichersn/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/usr/local/google/home/wichersn/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'data/breakout/120k/states.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

I don't see the `data/breakout/120k/states.h5` file on github. Should I download it from somewhere or generate it somehow?

Thanks

**Comment by icrcno1** [comment]
I also got the similar problem and don`t know how to solve it.
